# Random Forest

## A cloth manufacturing company is interested to know about the segment or attributes causes high sale

## Importing Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.model_selection import train_test_split

## Importing the Data

In [2]:
company_data = pd.read_csv('/content/Company_Data.csv')
company_data

Sales  CompPrice  Income  Advertising  ...  Age  Education Urban   US
0     9.50        138      73           11  ...   42         17   Yes  Yes
1    11.22        111      48           16  ...   65         10   Yes  Yes
2    10.06        113      35           10  ...   59         12   Yes  Yes
3     7.40        117     100            4  ...   55         14   Yes  Yes
4     4.15        141      64            3  ...   38         13   Yes   No
..     ...        ...     ...          ...  ...  ...        ...   ...  ...
395  12.57        138     108           17  ...   33         14   Yes  Yes
396   6.14        139      23            3  ...   55         11    No  Yes
397   7.41        162      26           12  ...   40         18   Yes  Yes
398   5.94        100      79            7  ...   50         12   Yes  Yes
399   9.71        134      37            0  ...   49         16   Yes  Yes

[400 rows x 11 columns]

## Data Understanding

In [3]:
company_data.shape

(400, 11)

In [4]:
company_data.dtypes

Sales          float64
CompPrice        int64
Income           int64
Advertising      int64
Population       int64
Price            int64
ShelveLoc       object
Age              int64
Education        int64
Urban           object
US              object
dtype: object

In [5]:
company_data['ShelveLoc'] = company_data['ShelveLoc'].astype('category')
company_data['Urban'] = company_data['Urban'].astype('category')
company_data['US'] = company_data['US'].astype('category')

In [6]:
company_data.isna().sum()

Sales          0
CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
ShelveLoc      0
Age            0
Education      0
Urban          0
US             0
dtype: int64

In [7]:
print(company_data.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...  
395    False
396    False
397    False
398    False
399    False
Length: 400, dtype: bool


In [8]:
company_data.describe(include='all')

Sales   CompPrice      Income  ...   Education  Urban   US
count   400.000000  400.000000  400.000000  ...  400.000000    400  400
unique         NaN         NaN         NaN  ...         NaN      2    2
top            NaN         NaN         NaN  ...         NaN    Yes  Yes
freq           NaN         NaN         NaN  ...         NaN    282  258
mean      7.496325  124.975000   68.657500  ...   13.900000    NaN  NaN
std       2.824115   15.334512   27.986037  ...    2.620528    NaN  NaN
min       0.000000   77.000000   21.000000  ...   10.000000    NaN  NaN
25%       5.390000  115.000000   42.750000  ...   12.000000    NaN  NaN
50%       7.490000  125.000000   69.000000  ...   14.000000    NaN  NaN
75%       9.320000  135.000000   91.000000  ...   16.000000    NaN  NaN
max      16.270000  175.000000  120.000000  ...   18.000000    NaN  NaN

[11 rows x 11 columns]

In [9]:
company_data['High'] = company_data['Sales'].map(lambda x: 1 if x>8 else 0)
company_data['ShelveLoc'] = company_data['ShelveLoc'].cat.codes
company_data['Urban'] = company_data['Urban'].cat.codes
company_data['US'] = company_data['US'].cat.codes
company_data

Sales  CompPrice  Income  Advertising  ...  Education  Urban  US  High
0     9.50        138      73           11  ...         17      1   1     1
1    11.22        111      48           16  ...         10      1   1     1
2    10.06        113      35           10  ...         12      1   1     1
3     7.40        117     100            4  ...         14      1   1     0
4     4.15        141      64            3  ...         13      1   0     0
..     ...        ...     ...          ...  ...        ...    ...  ..   ...
395  12.57        138     108           17  ...         14      1   1     1
396   6.14        139      23            3  ...         11      0   1     0
397   7.41        162      26           12  ...         18      1   1     0
398   5.94        100      79            7  ...         12      1   1     0
399   9.71        134      37            0  ...         16      1   1     1

[400 rows x 12 columns]

## Data Preparation

In [10]:
X=company_data.iloc[:,1:11]
y=company_data['High']
print(X)
print(y)

     CompPrice  Income  Advertising  Population  ...  Age  Education  Urban  US
0          138      73           11         276  ...   42         17      1   1
1          111      48           16         260  ...   65         10      1   1
2          113      35           10         269  ...   59         12      1   1
3          117     100            4         466  ...   55         14      1   1
4          141      64            3         340  ...   38         13      1   0
..         ...     ...          ...         ...  ...  ...        ...    ...  ..
395        138     108           17         203  ...   33         14      1   1
396        139      23            3          37  ...   55         11      0   1
397        162      26           12         368  ...   40         18      1   1
398        100      79            7         284  ...   50         12      1   1
399        134      37            0          27  ...   49         16      1   1

[400 rows x 10 columns]
0      1
1     

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size= 0.1,random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((360, 10), (40, 10), (360,), (40,))

## Model Builing

In [12]:
rf_model=RandomForestClassifier()

## Finding out the best hyperparameter for building the Tree


In [13]:
from sklearn.model_selection import GridSearchCV

In [14]:
grid_search = GridSearchCV(estimator = rf_model, param_grid = {'criterion':['gini','entropy'],'max_depth':[2,3,4,5,6,7,8,9,10,11,12]} , cv= 5)
grid_search

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]})

In [15]:
grid_search.fit(X,y)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]})

In [16]:
grid_search.best_params_

{'criterion': 'entropy', 'max_depth': 9}

In [17]:
grid_search.best_score_

0.8099999999999999

## Model Training

In [18]:
rf_model = RandomForestClassifier(criterion= 'entropy', max_depth=9)

In [19]:
rf_model.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=9)

## Model Testing

In [20]:
y_pred_train = rf_model.predict(X_train)

In [21]:
y_pred_test = rf_model.predict(X_test)

## Model Evaluation

## Confusion_Matrix :- To know the Misclassification done by the model

In [22]:
accuracy_score(y_train,y_pred_train)

1.0

In [23]:
confusion_matrix(y_train,y_pred_train)

array([[215,   0],
       [  0, 145]])

In [24]:
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       215
           1       1.00      1.00      1.00       145

    accuracy                           1.00       360
   macro avg       1.00      1.00      1.00       360
weighted avg       1.00      1.00      1.00       360



In [25]:
accuracy_score(y_test,y_pred_test)

0.725

In [26]:
confusion_matrix(y_test,y_pred_test)

array([[17,  4],
       [ 7, 12]])

In [27]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.71      0.81      0.76        21
           1       0.75      0.63      0.69        19

    accuracy                           0.73        40
   macro avg       0.73      0.72      0.72        40
weighted avg       0.73      0.72      0.72        40



# Model Improvement 1 : AdaBoost

In [28]:
from sklearn.ensemble import AdaBoostClassifier

## Model Builing and Model Training

In [29]:
ad_model = AdaBoostClassifier()

In [30]:
ad_model.fit(X_train,y_train)

AdaBoostClassifier()

## Model Testing

In [31]:
y_pred_train_d1 = ad_model.predict(X_train)

In [32]:
y_pred_test_d1 = ad_model.predict(X_test)

## Model Evaluation

## Confusion_Matrix :- To know the Misclassification done by the model

In [33]:
accuracy_score(y_train,y_pred_train_d1)

0.9666666666666667

In [34]:
confusion_matrix(y_train,y_pred_train_d1)

array([[210,   5],
       [  7, 138]])

In [35]:
print(classification_report(y_train,y_pred_train_d1))

              precision    recall  f1-score   support

           0       0.97      0.98      0.97       215
           1       0.97      0.95      0.96       145

    accuracy                           0.97       360
   macro avg       0.97      0.96      0.97       360
weighted avg       0.97      0.97      0.97       360



In [36]:
accuracy_score(y_test,y_pred_test_d1)

0.75

In [37]:
confusion_matrix(y_test,y_pred_test_d1)

array([[18,  3],
       [ 7, 12]])

In [38]:
print(classification_report(y_test,y_pred_test_d1))

              precision    recall  f1-score   support

           0       0.72      0.86      0.78        21
           1       0.80      0.63      0.71        19

    accuracy                           0.75        40
   macro avg       0.76      0.74      0.74        40
weighted avg       0.76      0.75      0.75        40



## Model Improvement 2 : GradientBoosting

In [39]:
from sklearn.ensemble import GradientBoostingClassifier

## Model Builing and Model Training

In [40]:
gr_model =GradientBoostingClassifier()

In [41]:
gr_model.fit(X_train,y_train)

GradientBoostingClassifier()

## Model Testing

In [42]:
y_pred_train_d2 = gr_model.predict(X_train)

In [43]:
y_pred_test_d2 = gr_model.predict(X_test)

## Model Evaluation

## Confusion_Matrix :- To know the Misclassification done by the model

In [44]:
accuracy_score(y_train,y_pred_train_d2)

0.9944444444444445

In [45]:
confusion_matrix(y_train,y_pred_train_d2)

array([[215,   0],
       [  2, 143]])

In [46]:
print(classification_report(y_train,y_pred_train_d2))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       215
           1       1.00      0.99      0.99       145

    accuracy                           0.99       360
   macro avg       1.00      0.99      0.99       360
weighted avg       0.99      0.99      0.99       360



In [47]:
accuracy_score(y_test,y_pred_test_d2)

0.85

In [48]:
confusion_matrix(y_test,y_pred_test_d2)

array([[19,  2],
       [ 4, 15]])

In [49]:
print(classification_report(y_test,y_pred_test_d2))

              precision    recall  f1-score   support

           0       0.83      0.90      0.86        21
           1       0.88      0.79      0.83        19

    accuracy                           0.85        40
   macro avg       0.85      0.85      0.85        40
weighted avg       0.85      0.85      0.85        40



## Model Deployment

In [50]:
from pickle import dump

In [51]:
dump(ad_model, open('Random_Forest(Company_data)','wb'))

In [52]:
from pickle import load

In [53]:
ad_model = load(open('/content/Random_Forest(Company_data)','rb'))

In [54]:
ad_model.predict(X_test)

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0])

## Model Done with AdaBoostClassifier is having Accracy score of 86.25%
## In classification_report It shows that model with AdaBoostClassifier having Better score in precision and f1-score compaired with other Models used here.